# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sito web del Ninja Coder di Rimini
email: coderdojoriminidev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Questo è un sito di prova realizzato dai Ninja del Coderdojo di Rimini (Italy).
  Realizziamo la struttura e le pagine e impariamo come gestire e aggiornare un semplice sito web oltre che alcuni linguaggi di marcatura.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ninja-rimini.github.io" # the base hostname & protocol for your site
twitter_username: coderdojoRN
github_username:  ninja-rimini

# Build settings
markdown: kramdown
